#!/bin/sh

### BEGIN INIT INFO
# Provides:          check ip
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start check ip
# Description:       start check ip
### END INIT INFO

case $1 in
        start)
                su pi -c 'octoprint & python /home/pi/checkip/app.py'
                ;;
        stop)
                kill $(ps aux | grep -m 1 'python /home/pi/checkip/app.py' | awk '{ print $2 }')
				;;
        *)
                echo "Usage: $0 (start|stop)"
                ;;
esac
exit 0
